### ISSUE TITLE
Improve zectl description

### ISSUE THREAD

**Issue by kovetskiy** [johnramsden/zectl#10]
Hi, could you please elaborate on what the program does and how does it work? Is it a sort of replacement for Grub? Will I be able to use different kernels and have the ability to choose between them?

**Comment by tlaguz** [comment]
This is like beadm in FreeBSD

**Comment by evelynmitchell** [comment]
My understanding is that this will allow you to easily manage snapshot and rollback of the filesystem during boot, so you would be able to do an update, and if it failed, recover to the previous running system.

**Comment by zhimsel** [comment]
You are both correct! It essentially creates a clone of your root filesystem and creates bootloader entries (if configured and supported) to allow booting into the clone. This is useful to do before upgrading or changing system components like the kernel, init manager, etc.

Note: the README for this program does explain this, though I suppose it could be improved. @kovetskiy was there anything specific that you didn't understand or found missing? I'd be happy to take a stab at improving it.

**Comment by zhimsel** [comment]
@kovetskiy feel free to reopen this if you would like to clarify the above question.
