### ISSUE TITLE
zectl activate shows the wrong boot environment as active

### ISSUE THREAD

**Issue by rpthms** [johnramsden/zectl#11]
When I have a single boot environment, I get N and R under the ACTIVE column for that boot environment as expected

    $ zectl list
    Name     Active  Mountpoint  Creation
    default  NR      /                 2020-03-21 11:28

After creating a new boot environment, zectl list shows the new boot environment and the ACTIVE column still shows N and R under the current boot environment, again as expected.

    $ sudo zectl create trial

    $ zectl list
    Name     Active  Mountpoint  Creation
    default  NR      /                 2020-03-21 11:28
    trial            -                 2020-03-21 18:01

But after I run 'zectl activate trial', the N label goes on the trial boot environment and the R label remains on the default boot environment. Which means that zectl thinks that the 'trial' boot environment is the active boot environment and the 'default' boot environment is the one that will be used after reboot (Based on the info in: https://zedenv.readthedocs.io/en/latest/basic-usage.html). Shouldn't it be the other way round? i.e. 'default' being the current environment and 'trial' being the environment used after reboot

    $ sudo zectl activate trial

    $ zectl list
    Name     Active  Mountpoint  Creation          
    default  R       /                 2020-03-21 11:28  
    trial    N       -                 2020-03-21 18:01

**Comment by johnramsden** [comment]
Thanks, released 0.1.1 with the fix.
