### ISSUE TITLE
One entry for each Boot Environment

### ISSUE THREAD

**Issue by eoli3n** [johnramsden/zectl#14]
I'm new on ZFS, and so on ``zectl``.
I was thinking that it will create a systemd-boot entry for each BE to let me choose on which one i want to rollback.
It seems that i need to use ``activate`` subcommand while system is running to let me reboot on that BE.

Problem is that it is not breakproof, if i ``rm -Rf *`` i can't boot on a precedent BE to recover.

I'm trying to implement something near how [NixOS generations](https://nixos.wiki/wiki/NixOS#Generations) works. Like writting a pacman hook to create a BE at each upgrade. Do I need to generate a systemd-boot entry manually, changing ``zfs=`` value ? Will this even work ?

**Comment by zhimsel** [comment]
Are you on the latest version? Simply creating a BE should create a bootloader entry, too.

**Comment by eoli3n** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zectl#n4
I use ``0.1.1-1``.

Here my configuration : https://github.com/eoli3n/arch-config/tree/master/ansible/roles/zfs/systemd-boot-zectl

**Comment by zhimsel** [comment]
`mount` won't show the path for a bind mount, only the root device.

Set the following dataset properties on your `<pool>/ROOT` dataset:
```
org.zectl.systemdboot:efi /efi
org.zectl.systemdboot:boot /boot
```

**Comment by johnramsden** [comment]
In terms of workflow, you could create a environment, reboot into it and do your upgrades there. What I have found more convenient is consider the default boot environment _always_ in use, and I do all my upgrades there. I don't usually activate another one unless I wanted to is a temporary for something.

Instead, prior to doing an upgrade I will create a boot environment with a name representing the current state, perhaps the kernel version, and then do my upgrade. If something goes wrong in the upgrade, I can choose a different option at boot, or activate the different environment.

Why are you trying to destroy the active boot environment? That won't be possible even with force. Force is more for the case where you have a already mounted boot environment somewhere else, and you want it forcefully unmounted and destroyed.

**Comment by johnramsden** [comment]
@eoli3n Also to clarify, when you create a new boot environment are you not getting a configuration file?

**Comment by eoli3n** [comment]
I want to use boot environment to be able to boot a previous state to recover. I note that it's better to use a ``pre`` pacman hook. I want to be able to ``snapshot`` current state at any moment, and boot without anything more any of these.

> Why are you trying to destroy the active boot environment?

Why not ? See that there it seems to be nothing to ``deactivate``. I activated but not booted it so is that problematic to deactivate ?

From the man:

> The Active column displays an N on the boot environment currently booted, and a R on the activate boot environment.

As it is not booted, why can't i deactivate and remove a boot environment that i don't want to keep anymore ?

> Also to clarify, when you create a new boot environment are you not getting a configuration file?
```
❯ zectl create test
zectl: Failed to run 'zectl create'.
Failed to create snapshot zroot/ROOT/prepacman@2020-05-08-09:51:25.

~
❯ zectl list
Name       Active  Mountpoint  Creation
prepacman  R       -                 2020-05-07 15:10
default    N       /                 2020-05-06 17:51
```

Something is unclear. From your README
> After creating a boot environment, when it is ready to be used, it is activated. After activation, once the system is rebooted, all new data will be stored in the new boot environment's dataset.

Ok, then i activated BE ``prepacman`` and rebooted, but as i didn't have systemd entry for that, i did boot my ``default`` BE. But i see that datas are written as said in the new BE...

```
❯ zfs list -o name,mountpoint,canmount,used
NAME                   MOUNTPOINT        CANMOUNT   USED
zroot                  none                   off  8,64G
zroot/ROOT             none                    on  7,57G
zroot/ROOT/default     /                   noauto   790M
zroot/ROOT/prepacman   /                   noauto  6,80G
zroot/data             /                      off  1,06G
zroot/data/home        /home                   on  1,06G
zroot/data/home/root   /root                   on  23,4M
zroot/var              /var                   off  2,02M
zroot/var/lib          /var/lib               off  1,32M
zroot/var/lib/docker   /var/lib/docker         on   744K
zroot/var/lib/libvirt  /var/lib/libvirt        on   416K
zroot/var/log          /var/log                on   524K
```
I don't get what ``activate`` does. What is the diff between ``activate`` and ``boot`` ?
``Boot`` is for me changing which root dataset is set in ``zfs=`` cmdline var.

That's a test host, i can break it.

**Comment by eoli3n** [comment]
> `mount` won't show the path for a bind mount, only the root device.
> 
> Set the following dataset properties on your `<pool>/ROOT` dataset:
> 
> ```
> org.zectl.systemdboot:efi /efi
> org.zectl.systemdboot:boot /boot
> ```
> 
> https://github.com/johnramsden/zectl/blob/master/docs/plugins/systemdboot.md

But why setting it as it is default value ? I will try anyway after i clarify what ``activate`` does.

**Comment by johnramsden** [comment]
Those properties aren't necessary, as you noted they are defaults.

Did you set:

```
zectl set bootloader=systemdboot
```

https://github.com/johnramsden/zectl/tree/master/docs/plugins

**Comment by eoli3n** [comment]
Did you see https://github.com/johnramsden/zectl/issues/14#issuecomment-625693712 ?
```
~
❯ zectl set bootloader=systemdboot

~
❯ zectl create test
zectl: Failed to run 'zectl create'.
Failed to run post-create hook

~
❯ zectl list
Name       Active  Mountpoint           Creation
prepacman  R       -                 2020-05-07 15:10
default    N       /                 2020-05-06 17:51
test               /tmp/ze.test.CUnGG62020-05-08 20:56

~
❯ zectl deactivate prepacman

zectl: Invalid input, no match found.

Usage:
zectl activate <boot environment>
zectl create [ -e <existing-dataset> | <existing-dataset@snapshot> ] [ -r ] <boot-environment>
zectl destroy [ -F ] <boot-environment>
zectl get [ -H ] [ property ]
zectl list
zectl mount <boot environment>
zectl rename <boot-environment> <boot-environment-new>
zectl set <property>=<value>
zectl snapshot <boot-environment>@<snapshot>
zectl unmount <boot-environment>
zectl version
```

**Comment by johnramsden** [comment]
Okay the requirements are:
* You enable the bootloader.
* You create a configuration that matches your currently active boot environment's name using the exact naming scheme mentioned in the documentation.
* You set up the blind mount, make sure the path to your EFI partition and boot are correct (or left at default), then you should be able to create a boot environment.

Please take another look at [docs/plugins/systemdboot.md](https://github.com/johnramsden/zectl/blob/master/docs/plugins/systemdboot.md).

If you've gone through all the above steps and you still cannot create an environment, there might be a bug, but you need to follow the setup steps completely for the plug-in hook to be properly run.

---

* There is no command deactivate, if you activate a different environment it will "deactivate" the old one.
* You can't destroy an activate environment.
* You can't destroy a currently booted environment.

If you want a point-in-time snapshot of your state, create a boot environment. Later if you want to go back to that state you activate it. If you want to install new upgrades into the new boot environment you of a few options:

* mount it and install packages into it without booting it
* activated and reboot into it then do your upgrades

But as I said before, but use your workflow where you don't need to reboot is you create a new environment, do not activate it, do your upgrades on your current system, if you want to go back to the state of the environment you created you can choose it at the boot menu.

**Comment by eoli3n** [comment]
Ok ok, but i still want ot know what ``activate`` does ?
If i reboot and select another systemd-boot entry with ``zfs=zroot/ROOT/testbe``, i will mount this as ``/`` and write on it. So why isn't it sufficient ?

**Comment by johnramsden** [comment]
Activate will:
* Promote the clone to a regular dataset.
* Change the bootloader so that it will be automatically booted next time.
* set of properties so it's considered the `zpool` bootfs.

You can certainly boot into a clone without activating it.

**Comment by eoli3n** [comment]
Lets verify everythings is ok:

```
[root@osz ~]# zectl get
PROPERTY                    VALUE
org.zectl:bootloader        systemdboot
org.zectl.systemdboot:efi   /efi
org.zectl.systemdboot:boot  /boot
org.zectl:bootpool_root
org.zectl:bootpool_prefix
[root@osz ~]# ls /efi
dc6d323dfcb146d4b79641866073ba33  EFI  env  loader
[root@osz ~]# ls /efi/env/org.zectl-default/
initramfs-linux-lts-fallback.img  initramfs-linux-lts.img  intel-ucode.img  vmlinuz-linux-lts
[root@osz ~]# cat /efi/loader/
entries/     loader.conf  random-seed
[root@osz ~]# cat /efi/loader/entries/
org.zectl-default.conf  recovery.conf
[root@osz ~]# cat /efi/loader/entries/org.zectl-default.conf
title           Arch Linux ZFS Default
linux           /env/org.zectl-default/vmlinuz-linux-lts
initrd          /env/org.zectl-default/intel-ucode.img
initrd          /env/org.zectl-default/initramfs-linux-lts.img
options         zfs=zroot/ROOT/default rw
[root@osz ~]# zectl create test
[root@osz ~]# ls /efi/loader/entries/
org.zectl-default.conf	org.zectl-test.conf  recovery.conf
[root@osz ~]# cat /efi/loader/entries/org.zectl-test.conf
title           Arch Linux ZFS Default
linux           /env/org.zectl-test/vmlinuz-linux-lts
initrd          /env/org.zectl-test/intel-ucode.img
initrd          /env/org.zectl-test/initramfs-linux-lts.img
options         zfs=zroot/ROOT/test rw
```

Now i create a BE:

```
[root@osz ~]# zectl create test

[root@osz ~]# ls /efi/loader/entries/
org.zectl-default.conf  org.zectl-test.conf  recovery.conf

[root@osz ~]# cat /efi/loader/entries/org.zectl-test.conf
title           Arch Linux ZFS Default
linux           /env/org.zectl-test/vmlinuz-linux-lts
initrd          /env/org.zectl-test/intel-ucode.img
initrd          /env/org.zectl-test/initramfs-linux-lts.img
options         zfs=zroot/ROOT/test rw
```

I want to restore it, so i reboot and select "test" bootloader entry in systemd-boot.
Then, to make the revert effective:

```
[root@osz ~]# zectl list
Name     Active  Mountpoint  Creation
default  R       -                 2020-05-09 11:13
test     N       /                 2020-05-09 12:33
[root@osz ~]# zectl activate test
[root@osz ~]# zectl list
Name     Active  Mountpoint  Creation
default          -                 2020-05-09 11:13
test     NR      /                 2020-05-09 12:33
[root@osz ~]# zectl destroy default
[root@osz ~]# zectl list
Name  Active  Mountpoint  Creation
test  NR      /                 2020-05-09 12:33
```

Let's reboot !
Ok that's working well if i do things how they need to be done :)

I tried to create a BE then ``rm -Rf /usr``, reboot on the BE, it worked !
Thanks for your help
