### ISSUE TITLE
fix aur PKGBUILD

### ISSUE THREAD

**Issue by eoli3n** [johnramsden/zectl#20]
I'm trying to build an AUR package which depends of yours:
https://github.com/eoli3n/zectl-pacman-hook/blob/master/PKGBUILD#L10

To let my package depends to ``zectl`` OR ``zectl-git`` packages, could you add ``provides`` key to your PKGBUILD please ?
See https://wiki.archlinux.org/index.php/PKGBUILD#provides

Adding this to https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zectl-git
```
provides=("zectl")
```

**Comment by eoli3n** [comment]
User earnestly@freenode#archlinux fixed some points and gave me that, feel free to use it or not :)

```
pkgname=zectl-git
pkgver=r114.45f9dc4
pkgrel=1
pkgdesc="ZFS Boot Environment manager"
url="http://github.com/johnramsden/zectl"
arch=('any')
license=('MIT')
depends=('zfs')
makedepends=('git' 'cmake')
provides=('zectl')
conflicts=('zectl')
source=('git+https://github.com/johnramsden/zectl')
sha256sums=(SKIP)

pkgver() {
	cd zectl
	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
    cd zectl
    CFLAGS+=" -fmacro-prefix-map=$PWD/=" cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DPLUGINS_DIRECTORY=/usr/share/zectl/libze_plugin .
    make VERBOSE=1
}

package() {
    cd zectl
    make DESTDIR="$pkgdir" install
    install -Dm0644 docs/zectl.8 "$pkgdir"/usr/share/man/man8/zectl.8
    install -Dm0644 README.md "$pkgdir"/usr/share/doc/"$pkgname"/README.md
    install -Dm0644 LICENSE "$pkgdir"/usr/share/licenses/"$pkgname"/LICENSE-MIT
}
```

**Comment by johnramsden** [comment]
Sure, added.

Thanks, those are some nice improvements to remove the:

> ==> WARNING: Package contains reference to $srcdir

I pushed both packages. Let me know if you run into any other issues.
