### ISSUE TITLE
bieaz: another BE manager

### ISSUE THREAD

**Issue by ne9z** [johnramsden/zectl#38]
Hi John!

This is not really a issue for `zectl` actually, but I think it could provide some new ideas for the development.

Due to the lack of support of separate boot pool, among others, I end up writing my own script-based BE manager, [bieaz](https://gitlab.com/m_zhou/bieaz), partially based on [beadm](https://github.com/vermaden/beadm).

- It supports separate `/boot` pool, thus all ZFS features can be enabled on root pool, such as encryption. The guide below supports encryption.
- Arbitrary dataset paths like `rpool/a/b/c/bootenv` via [parameter expansion](https://pubs.opengroup.org/onlinepubs/007904875/utilities/xcu_chap02.html).

[A complete root on ZFS installation guide for Arch Linux](https://github.com/ne9z/openzfs-docs/blob/arch-support/docs/Getting%20Started/Arch%20Linux/Arch%20Linux%20Root%20on%20ZFS.rst) has also been submitted as [a pull request](https://github.com/openzfs/openzfs-docs/pull/104) to `openzfs-docs` repo.

The main difference between `bieaz` and other BE managers is that, `bootfs` property is not used. 

Instead, root filesystem dataset is identified with `root=ZFS=pool/ROOT/dataset` kernel command line at boot. This enables the selection of boot environments at boot. A boot menu is possible.

Currently GRUB integration is completed. Boot environments can be selected within GRUB menu.

![GRUB_1](https://user-images.githubusercontent.com/77314501/104458925-e8481380-55a3-11eb-8f23-84a982403f55.png)
![GRUB_2](https://user-images.githubusercontent.com/77314501/104458938-eb430400-55a3-11eb-8973-9b4dcbabf2e6.png)

**Comment by johnramsden** [comment]
It's great to see there's a new option for people who need grub support, congratulations on your project.

I'm not against adding grab support, I just don't currently have the time to add the plugin myself. Previously multiple people have taken an interest in doing the work but then have not been able to take it to completion, or I lost contact with them.

If you're interested in potentially working together, I think we could probably integrate the grub hook script you currently have into a grub plugin, if you're not proficient in C I could add required parts for the C section, or support you.

Let me know if you're interested in working together, but either way congratulations on your project.

**Comment by ne9z** [comment]
GRUB support is quite easy, I should say. 

Just mount the dataset, tell GRUB the mount point and it will detect `initramfs`, `vmlinuz` and microcode automatically.

This is a synopsis of [my GRUB script](https://gitlab.com/m_zhou/bieaz/-/blob/master/42_bieaz):
```
. "/usr/share/bieaz/zfs_layout" # determine root and boot dataset.
. "/usr/share/bieaz/10_linux" # identical copy of /etc/grub.d/10_linux

__snapshot_list () {} # list available boot environments

main() {
for i in $(__snapshot_list); do
     boot_dir=$(bieaz mount $i) # tell GRUB this mount point is /boot
     __let_grub_do_its_work
     bieaz umount $i
done
}

main # entry point
```
