### ISSUE TITLE
Pacman hook

### ISSUE THREAD

**Issue by schmitmd** [johnramsden/zectl#40]
Hey there, just wanted to share something that might be cool to toss in the documentation.  Manually creating boot envs every time I upgrade my kernel was something difficult to remember whenever running pacman on Arch, so I wrote a little hook to make one for me on each upgrade.  It's not perfect, but might be helpful to someone besides me.

Uncomment the "HookDir" config directive in /etc/pacman.conf, then make a `/etc/pacman.d/hooks/10-zectl.hook` file. Put the following in it:
```
[Trigger]
Type = Package
Operation = Install
Operation = Upgrade
Target = linux linux-lts

[Trigger]
Type = Path
Operation = Install
Operation = Upgrade
Target = usr/lib/modules/*/vmlinuz

[Action]
Description = Creating Boot Environment...
When = PreTransaction
Exec = /etc/pacman.d/scripts/zectl_create
```
and make a `/etc/pacman.d/scripts/zectl_create` script with something simple like:
```bash
#!/bin/bash
/usr/sbin/zectl create $(uname -r)
```

**Comment by eoli3n** [comment]
I did this : https://github.com/eoli3n/zectl-pacman-hook
