### ISSUE TITLE
Failed to run post-create hook with systemdboot

### ISSUE THREAD

**Issue by junky89** [johnramsden/zectl#41]
Hi,

I'm running Arch installed on zfs on root that I install it using the ALEZ script (systemd-boot as bootloader). I'm trying to use zectl with systemdboot plugin. I enabled it as `zectl set bootloader=systemdboot`. 

When I try to create an snapshot with for example `zectl create snapshot1` an error occurs:
```
zectl: Failed to run 'zectl create'.
Failed to run post-create hook
```

After that, if I do `zectl list` I get:
```
Name       Active  Mountpoint                Creation          
snapshot1          /tmp/ze.snapshot1.tivoaW2021-05-25 22:25  
default    NR      /                 2021-05-25 18:58
```

The output of `zfs list` is:
```
zroot                 7.76G   891G      176K  none
zroot/ROOT            7.52G   891G      176K  none
zroot/ROOT/default    7.52G   891G     7.50G  /
zroot/ROOT/snapshot1     8K   891G     7.50G  /tmp/ze.snapshot1.tivoaW
zroot/data             245M   891G      176K  none
zroot/data/home        245M   891G      245M  legacy
```

But I can't see any logs or output of the error anywhere, so I'm a bit lost on what is the problem.

**Comment by johnramsden** [comment]
Are you setup according to [docs/plugins/systemdboot.md](https://github.com/johnramsden/zectl/blob/master/docs/plugins/systemdboot.md) ?

What does `zectl get` output?

**Comment by junky89** [comment]
Sorry but at the end and after several formats I just went with grub and zedenv and now is working fine. Next time I format maybe I try again.
