### ISSUE TITLE
Failed to run post-create hook with systemdboot

### ISSUE THREAD

**Issue by Von-Birne** [johnramsden/zectl#42]
Hey,

it seems like I do have the same issue as [#41].
I followed the docs but the post-create hook fails after a snapshot gets created and mounted.

`zectl get` outputs this:
```
PROPERTY                                       VALUE               
org.zectl:bootloader                           systemdboot         
org.zectl.systemdboot:efi                      /efi                
org.zectl.systemdboot:boot                     /boot               
org.zectl.systemdboot:kernelsnapshotdirectory  /zectl/systemdboot  
org.zectl:bootpoolroot                                             
org.zectl:bootpoolprefix                                           
```

The only error I get is
```
zectl: Failed to run 'zectl create'.
Failed to run post-create hook
```

I might have overlooked something in the guide but I cannot figure it out.

Best wishes!

**Comment by johnramsden** [comment]
Can you post output from:
* `zfs list`
* `find /efi/loader`

**Comment by Von-Birne** [comment]
Here is `zectl list`:
```
Name     Active  Mountpoint           Creation          
test             /tmp/ze.test.gI4MkJ2021-06-30 19:04  
default  NR      /                 2021-06-25 19:52  
```
`zfs list`:
```
NAME                                USED  AVAIL     REFER  MOUNTPOINT
zroot                              9.01G   913G       96K  none
zroot/arch                         9.00G   913G       96K  none
zroot/arch/DATA                    2.92G   913G       96K  none
zroot/arch/DATA/default            2.92G   913G       96K  /
zroot/arch/DATA/default/home       2.92G   913G     2.92G  /home
zroot/arch/DATA/default/root        172K   913G      172K  /root
zroot/arch/DATA/default/srv          96K   913G       96K  /srv
zroot/arch/DATA/default/usr         244K   913G       96K  /usr
zroot/arch/DATA/default/usr/local   148K   913G      148K  /usr/local
zroot/arch/DATA/default/var         772K   913G       96K  /var
zroot/arch/DATA/default/var/lib      96K   913G       96K  /var/lib
zroot/arch/DATA/default/var/log     484K   913G      484K  /var/log
zroot/arch/DATA/default/var/spool    96K   913G       96K  /var/spool
zroot/arch/ROOT                    6.07G   913G       96K  none
zroot/arch/ROOT/default            6.07G   913G     5.74G  /
zroot/arch/ROOT/test                  8K   913G     5.74G  /tmp/ze.test.gI4MkJ
```
`find /efi/loader`:
```
/efi/loader/
/efi/loader/entries
/efi/loader/entries/arch.conf
/efi/loader/loader.conf
/efi/loader/random-seed
```

**Comment by johnramsden** [comment]
I see the issue, For the initial environment you need to match the naming structure so it can copy `default`, see in the documentation: 

> Copy your current kernels to `$esp/env/org.zectl-<boot environment>/`
> 
> The bootloader configuration can now use a different path for each boot
> environment.
> 
> So the 'default' boot environment config, located at
> `$esp/loader/entries/org.zectl-default.conf`, would look something like:
> 
> ```
> title           Arch Linux
> linux           /env/org.zectl-default/vmlinuz-linux
> initrd          /env/org.zectl-default/intel-ucode.img
> initrd          /env/org.zectl-default/initramfs-linux.img
> options         zfs=zpool/ROOT/default rw
> ```
> 
> Create this configuration file.
> 
> To make the system happy when it looks for kernels at `/boot`, this directory
> should be bindmounted to `/boot`.
> 
> If your system uses a different directory for kernels it can be set with:
> 
> ```shell script
> $ zectl set systemdboot:boot=<kernel directory>
> ```
> 
> Bindmount `$esp/env/org.zectl-default` to `/boot` in `/etc/fstab`.
> 
> ```
> /efi/env/org.zectl-default   /boot     none    rw,defaults,errors=remount-ro,bind    0 0
> ```
> 
> If this directory is not here, the kernels will not be updated when the system
> rebuilds the kernel.
> 
> Once a system is set up in the proper configuration, `zectl` will update
> the bootloader, and fstab when a new boot environment is created.
> 
> It will also copy the configuration described above, replacing the currently
> activated boot environment's configuration with the new boot environments name.

So you need to:

1. Create `/efi/loader/entries/org.zectl-default.conf`
2. Create dir `/efi/env/org.zectl-default`
3. Copy your existing kernel to `/efi/env/org.zectl-default`, and adjust your config accordingly. 
4. Bindmount `/efi/env/org.zectl-default` -> `/boot` 
5. Update fstab

**Comment by Von-Birne** [comment]
Thank you very much for the fast help. I indeed forgot to rename my bootloader entrie and now everything works perfekt.
