### ISSUE TITLE
Build failing with gcc 14.1.1

### ISSUE THREAD

**Issue by woodsb02** [johnramsden/zectl#54]
This build is failing for me on ArchLinux (gcc 14.1.1) with the following error:

`zectl/src/zectl-0.1.3/lib/libze/libze.c:596:35: error: passing argument 2 of ‘nvpair_value_string’ from incompatible pointer type [-Wincompatible-pointer-types]
...
/usr/include/libzfs/sys/nvpair.h:291:57: note: expected ‘const char **’ but argument is of type ‘char **’`

I found that adding -fpermissive to CFLAGS solved this, but this feels like more of a work around than fixing the issue.

**Comment by johnramsden** [comment]
@woodsb02 Fixed in #53 and 0.1.4
